### ISSUE TITLE
Add new tracking events

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#514]
As a marketer
So that I can more closely track how people are interacting with pages
I want to a js library to can send custom analytics events to segment based on when the user clicks on parts of the page

At the moment this is done as a [one-off in all.js](https://github.com/makersacademy/website/blob/master/source/javascripts/all.js#L40) but we need this more generically as it's required a lot on the ronin website.

Once it's done we should track the following events on the website:

- [ ] Grad slider clicked
- [ ] Curriculum slider clicked
- [ ] Alumni videos watched

**Comment by pitchinvasion** [comment]
We also need to ensure that every event on the website/ronin website has `Course Type "Offline"`

**Comment by pitchinvasion** [comment]
Use data attributes to know what needs to be tracked

**Comment by pitchinvasion** [comment]
We also need to do this for the employers page button

**Comment by silvabox** [comment]
Irina and I assigned

**Comment by silvabox** [comment]
@pitchinvasion which employers page button?  Hire?
